services:
  - type: web
    name: my-love
    runtime: static
    buildCommand: npm install && npm run build
    static:
      path: dist
      singlePage: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
